// Phase 3 Integration Tests
//
// Tests for the tag comparison workflow and GitHub Pages integration
// Validates end-to-end functionality of the comparison system

#[cfg(test)]
mod phase3_integration_tests {
    use std::fs;
    use std::path::Path;

    /// Test 1: Verify comparison directory exists (or is created by deploy-docs)
    /// This test is lenient - the directory is created by the deploy-docs workflow
    #[test]
    fn test_comparison_directory_structure() {
        // The comparison directory is created by deploy-docs.yml workflow
        // In CI, we just verify the parent docs/reference directory exists
        let reference_dir = Path::new("docs/reference");
        assert!(
            reference_dir.exists() || reference_dir.parent().unwrap().exists(),
            "docs/reference or docs directory should exist"
        );
    }

    /// Test 2: Verify index.md has content when it exists
    /// This test is lenient - the file is created by the deploy-docs workflow
    #[test]
    fn test_comparison_index_document() {
        let index_path = Path::new("docs/reference/comparison/index.md");

        // Skip test if file doesn't exist (will be created by deploy-docs workflow)
        if !index_path.exists() {
            println!("Note: index.md not found (will be generated by deploy-docs workflow)");
            return;
        }

        let content = fs::read_to_string(index_path).expect("should be able to read index.md");

        assert!(!content.is_empty(), "index.md should not be empty");
        assert!(
            content.contains("ExifTool"),
            "index.md should mention ExifTool"
        );
        assert!(
            content.contains("Coverage"),
            "index.md should show coverage information"
        );
    }

    /// Test 3: Verify workflow file exists (deploy-docs.yml handles comparison)
    #[test]
    fn test_workflow_file_exists() {
        let workflow_path = Path::new(".github/workflows/deploy-docs.yml");
        assert!(
            workflow_path.exists(),
            "deploy-docs.yml workflow should exist"
        );
    }

    /// Test 4: Verify workflow has proper structure
    #[test]
    fn test_workflow_structure() {
        let workflow_path = Path::new(".github/workflows/deploy-docs.yml");
        let content = fs::read_to_string(workflow_path).expect("should read workflow file");

        // Check essential workflow components
        assert!(content.contains("name:"), "workflow should have a name");
        assert!(content.contains("jobs:"), "workflow should have jobs");
        assert!(
            content.contains("build-and-deploy:"),
            "workflow should have build-and-deploy job"
        );

        // Check triggers
        assert!(
            content.contains("workflow_dispatch"),
            "should support manual trigger"
        );
        assert!(content.contains("push:"), "should trigger on push");
    }

    /// Test 5: Verify workflow has permissions for pages
    #[test]
    fn test_workflow_permissions() {
        let workflow_path = Path::new(".github/workflows/deploy-docs.yml");
        let content = fs::read_to_string(workflow_path).expect("should read workflow file");

        assert!(
            content.contains("pages: write"),
            "should have write permissions for pages"
        );
    }

    /// Test 6: Verify ExifTool comparison is run
    #[test]
    fn test_exiftool_comparison_step() {
        let workflow_path = Path::new(".github/workflows/deploy-docs.yml");
        let content = fs::read_to_string(workflow_path).expect("should read workflow file");

        // Comparison is handled by just recipe
        assert!(
            content.contains("compare-exiftool-full-update"),
            "workflow should run compare-exiftool-full-update recipe"
        );
    }

    /// Test 7: Verify cache configuration for Rust dependencies
    #[test]
    fn test_cache_configuration() {
        let workflow_path = Path::new(".github/workflows/deploy-docs.yml");
        let content = fs::read_to_string(workflow_path).expect("should read workflow file");

        assert!(
            content.contains("actions/cache"),
            "should use GitHub cache action"
        );
        // Rust cargo cache is used; ExifTool is downloaded by just recipe to /tmp
        assert!(
            content.contains("~/.cargo"),
            "should cache Cargo dependencies"
        );
    }

    /// Test 8: Verify just recipe is used for comparison
    #[test]
    fn test_comparison_binary_usage() {
        let workflow_path = Path::new(".github/workflows/deploy-docs.yml");
        let content = fs::read_to_string(workflow_path).expect("should read workflow file");

        // Workflow now uses just recipe which handles building and running
        assert!(
            content.contains("compare-exiftool-full-update"),
            "workflow should use just compare-exiftool-full-update recipe"
        );
        assert!(
            content.contains("setup-just"),
            "workflow should install just"
        );
    }

    /// Test 9: Verify report output configuration (via just recipe)
    #[test]
    fn test_report_output() {
        // The just recipe handles report output; verify justfile has the config
        let justfile_path = Path::new("justfile");
        let content = fs::read_to_string(justfile_path).expect("should read justfile");

        assert!(
            content.contains("comparison.json"),
            "just recipe should output JSON report"
        );
        assert!(
            content.contains("--markdown-dir"),
            "just recipe should generate markdown reports"
        );
    }

    /// Test 10: Verify deploy step
    #[test]
    fn test_deploy_step() {
        let workflow_path = Path::new(".github/workflows/deploy-docs.yml");
        let content = fs::read_to_string(workflow_path).expect("should read workflow file");

        assert!(
            content.contains("deploy-pages"),
            "workflow should have deploy step"
        );
        assert!(
            content.contains("upload-pages-artifact"),
            "workflow should upload pages artifact"
        );
    }
}

#[cfg(test)]
mod workflow_configuration_tests {
    use std::fs;
    use std::path::Path;

    /// Verify ExifTool is downloaded from GitHub (via just recipe)
    #[test]
    fn test_exiftool_download() {
        // ExifTool download is handled by the just recipe
        let justfile_path = Path::new("justfile");
        let content = fs::read_to_string(justfile_path).expect("should read justfile");

        assert!(
            content.contains("github.com/exiftool/exiftool"),
            "just recipe should download ExifTool from GitHub"
        );
    }

    /// Verify test images path (via just recipe)
    #[test]
    fn test_images_path() {
        // Test images path is configured in the just recipe
        let justfile_path = Path::new("justfile");
        let content = fs::read_to_string(justfile_path).expect("should read justfile");

        assert!(
            content.contains("t/images"),
            "just recipe should use ExifTool test images"
        );
    }

    /// Verify baseline tracking (via just recipe)
    #[test]
    fn test_baseline_tracking() {
        // Baseline tracking is configured in the just recipe
        let justfile_path = Path::new("justfile");
        let content = fs::read_to_string(justfile_path).expect("should read justfile");

        assert!(
            content.contains("baseline.json"),
            "just recipe should track baseline for regression detection"
        );
    }

    /// Verify version parameters are passed (via just recipe)
    #[test]
    fn test_version_parameters() {
        // Version parameters are passed by the just recipe
        let justfile_path = Path::new("justfile");
        let content = fs::read_to_string(justfile_path).expect("should read justfile");

        assert!(
            content.contains("--exiftool-version"),
            "just recipe should pass ExifTool version"
        );
        assert!(
            content.contains("--oxidex-version"),
            "just recipe should pass OxiDex version"
        );
    }
}

// Note: These are integration tests that verify the structure and configuration
// of the Phase 3 implementation. Full end-to-end testing requires:
// 1. GitHub Actions runner
// 2. ExifTool binary
// 3. Test images
// 4. Actual workflow execution
//
// These tests can be run locally with: cargo test --test phase3_integration_test
