//! Qualcomm MakerNote parser
//!
//! Parses Qualcomm Snapdragon camera-specific EXIF MakerNote tags containing
//! ISP (Image Signal Processor) computational photography settings and
//! Qualcomm-exclusive camera features.
//!
//! ## Supported Features
//! - Clear Sight dual-camera fusion
//! - Chroma Flash multi-frame blending
//! - OptiZoom digital zoom enhancement
//! - HDR mode settings
//! - Multi-frame noise reduction
//! - AI scene detection
//! - Bokeh depth processing
//! - Low-light enhancement
//!
//! ## Architecture
//! Qualcomm's MakerNotes are generated by the Snapdragon ISP and contain
//! metadata about computational photography features available on devices
//! using Qualcomm chipsets. These tags are manufacturer-agnostic but specific
//! to Qualcomm's camera pipeline.

#![allow(dead_code)]
#![allow(unused_imports)]

use crate::parsers::tiff::ifd_parser::{ByteOrder, IfdEntry};
use std::collections::HashMap;

use super::shared::array_extractors::extract_i16_array;
use super::shared::MakerNoteParser;

// Qualcomm MakerNote Tag IDs
// Note: Qualcomm's tag structure is proprietary and reverse-engineered
const QUALCOMM_CLEAR_SIGHT: u16 = 0x0001; // Clear Sight fusion status
const QUALCOMM_CLEAR_SIGHT_MODE: u16 = 0x0002; // Fusion mode variant
const QUALCOMM_CHROMA_FLASH: u16 = 0x0004; // Chroma Flash status
const QUALCOMM_CHROMA_FLASH_FRAMES: u16 = 0x0005; // Number of frames used
const QUALCOMM_OPTIZOOM: u16 = 0x0007; // OptiZoom enhancement
const QUALCOMM_ZOOM_LEVEL: u16 = 0x0008; // Digital zoom level (10x = 100)
const QUALCOMM_HDR_MODE: u16 = 0x000A; // HDR processing mode
const QUALCOMM_MULTI_FRAME_NR: u16 = 0x000C; // Multi-frame noise reduction
const QUALCOMM_SCENE_DETECTION: u16 = 0x000E; // AI scene detection
const QUALCOMM_BOKEH_MODE: u16 = 0x0010; // Bokeh depth processing
const QUALCOMM_BOKEH_LEVEL: u16 = 0x0011; // Bokeh blur amount
const QUALCOMM_LOW_LIGHT_MODE: u16 = 0x0013; // Low-light enhancement
const QUALCOMM_NIGHT_MODE: u16 = 0x0015; // Night mode processing
const QUALCOMM_PHASE_DETECT_AF: u16 = 0x0017; // Phase detection AF status
const QUALCOMM_ISP_VERSION: u16 = 0x0019; // Snapdragon ISP version
const QUALCOMM_FRAME_MERGE_COUNT: u16 = 0x001B; // Merged frame count

// Qualcomm signature for validation
const QUALCOMM_SIGNATURE: &[u8] = b"Qualcomm";

/// Decodes Clear Sight dual-camera fusion status
///
/// # Arguments
/// * `value` - Clear Sight status value
///
/// # Returns
/// Human-readable status description
fn decode_clear_sight(value: i16) -> String {
    match value {
        0 => "Off".to_string(),
        1 => "On".to_string(),
        2 => "Auto".to_string(),
        _ => format!("Unknown ({})", value),
    }
}

/// Decodes Clear Sight fusion mode variant
///
/// # Arguments
/// * `value` - Fusion mode value
///
/// # Returns
/// Human-readable mode description
fn decode_clear_sight_mode(value: i16) -> String {
    match value {
        0 => "None".to_string(),
        1 => "Monochrome + RGB Fusion".to_string(),
        2 => "Wide + Telephoto Fusion".to_string(),
        3 => "Multi-Camera Fusion".to_string(),
        _ => format!("Unknown ({})", value),
    }
}

/// Decodes Chroma Flash status
///
/// # Arguments
/// * `value` - Chroma Flash status
///
/// # Returns
/// Human-readable status
fn decode_chroma_flash(value: i16) -> String {
    match value {
        0 => "Off".to_string(),
        1 => "Flash + No Flash Blend".to_string(),
        2 => "Multi-Flash Blend".to_string(),
        _ => format!("Unknown ({})", value),
    }
}

/// Decodes HDR mode
///
/// # Arguments
/// * `value` - HDR mode value
///
/// # Returns
/// Human-readable mode description
fn decode_hdr_mode(value: i16) -> String {
    match value {
        0 => "Off".to_string(),
        1 => "HDR".to_string(),
        2 => "Auto HDR".to_string(),
        3 => "HDR+".to_string(),
        4 => "Staggered HDR".to_string(),
        _ => format!("Unknown ({})", value),
    }
}

/// Decodes AI scene detection result
///
/// # Arguments
/// * `value` - Scene type value
///
/// # Returns
/// Human-readable scene description
fn decode_scene_type(value: i16) -> String {
    match value {
        0 => "None".to_string(),
        1 => "Portrait".to_string(),
        2 => "Landscape".to_string(),
        3 => "Food".to_string(),
        4 => "Night".to_string(),
        5 => "Sunset".to_string(),
        6 => "Beach".to_string(),
        7 => "Snow".to_string(),
        8 => "Flower".to_string(),
        9 => "Pet".to_string(),
        10 => "Document".to_string(),
        _ => format!("Unknown ({})", value),
    }
}

/// Decodes OptiZoom enhancement level
///
/// # Arguments
/// * `value` - OptiZoom level
///
/// # Returns
/// Human-readable level description
fn decode_optizoom(value: i16) -> String {
    match value {
        0 => "Off".to_string(),
        1 => "Low".to_string(),
        2 => "Medium".to_string(),
        3 => "High".to_string(),
        4 => "Maximum".to_string(),
        _ => format!("Unknown ({})", value),
    }
}

/// Decodes zoom level
///
/// # Arguments
/// * `value` - Zoom level (10 = 1.0x, 100 = 10.0x)
///
/// # Returns
/// Human-readable zoom level
fn decode_zoom_level(value: i16) -> String {
    if value <= 0 {
        return "1.0x".to_string();
    }
    let zoom = value as f32 / 10.0;
    format!("{:.1}x", zoom)
}

/// Extracts a 16-bit signed value from IFD entry
///
/// # Arguments
/// * `entry` - IFD entry containing the value
/// * `data` - Full MakerNote data buffer
/// * `byte_order` - Byte order for parsing
///
/// # Returns
/// Extracted value or None if invalid
fn extract_i16_value(entry: &IfdEntry, _data: &[u8], byte_order: ByteOrder) -> Option<i16> {
    if entry.value_count != 1 {
        return None;
    }

    // For SHORT type (count=1), value is inline in value_offset field
    let value = match byte_order {
        ByteOrder::LittleEndian => (entry.value_offset & 0xFFFF) as i16,
        ByteOrder::BigEndian => ((entry.value_offset >> 16) & 0xFFFF) as i16,
    };

    Some(value)
}

/// Extracts a 32-bit unsigned value from IFD entry
///
/// # Arguments
/// * `entry` - IFD entry containing the value
/// * `data` - Full MakerNote data buffer
/// * `byte_order` - Byte order for parsing
///
/// # Returns
/// Extracted value or None if invalid
fn extract_u32_value(entry: &IfdEntry, _data: &[u8], _byte_order: ByteOrder) -> Option<u32> {
    if entry.value_count != 1 {
        return None;
    }

    Some(entry.value_offset)
}

/// Extracts an ASCII string from IFD entry
///
/// # Arguments
/// * `entry` - IFD entry containing the string
/// * `data` - Full MakerNote data buffer
/// * `byte_order` - Byte order for parsing
///
/// # Returns
/// Extracted string or None if invalid
fn extract_string(entry: &IfdEntry, data: &[u8], byte_order: ByteOrder) -> Option<String> {
    if entry.value_count == 0 {
        return None;
    }

    let value_bytes = if entry.value_count <= 4 {
        // Inline string (stored in value_offset field)
        let mut bytes = Vec::new();
        for i in 0..entry.value_count as usize {
            let byte = match byte_order {
                ByteOrder::LittleEndian => ((entry.value_offset >> (i * 8)) & 0xFF) as u8,
                ByteOrder::BigEndian => ((entry.value_offset >> (24 - i * 8)) & 0xFF) as u8,
            };
            if byte == 0 {
                break;
            }
            bytes.push(byte);
        }
        bytes
    } else {
        // External string (offset points to data)
        let offset = entry.value_offset as usize;
        if offset >= data.len() {
            return None;
        }
        let end = std::cmp::min(offset + entry.value_count as usize, data.len());
        data[offset..end].to_vec()
    };

    if value_bytes.is_empty() {
        return None;
    }

    let string = String::from_utf8_lossy(&value_bytes)
        .trim_end_matches('\0')
        .to_string();

    if string.is_empty() {
        None
    } else {
        Some(string)
    }
}

/// Qualcomm MakerNote parser implementation
pub struct QualcommParser;

impl Default for QualcommParser {
    fn default() -> Self {
        Self::new()
    }
}

impl QualcommParser {
    /// Creates a new Qualcomm parser instance
    pub fn new() -> Self {
        QualcommParser
    }

    /// Parse a single IFD entry and extract tag value
    ///
    /// # Arguments
    /// * `entry` - IFD entry to parse
    /// * `data` - Full MakerNote data buffer
    /// * `byte_order` - Byte order for multi-byte values
    /// * `tags` - HashMap to insert extracted tags into
    fn parse_entry(
        &self,
        entry: &IfdEntry,
        data: &[u8],
        byte_order: ByteOrder,
        tags: &mut HashMap<String, String>,
    ) {
        let tag_id = entry.tag_id;

        match tag_id {
            QUALCOMM_CLEAR_SIGHT => {
                if let Some(value) = extract_i16_value(entry, data, byte_order) {
                    tags.insert("Qualcomm:ClearSight".to_string(), decode_clear_sight(value));
                }
            }
            QUALCOMM_CLEAR_SIGHT_MODE => {
                if let Some(value) = extract_i16_value(entry, data, byte_order) {
                    tags.insert(
                        "Qualcomm:ClearSightMode".to_string(),
                        decode_clear_sight_mode(value),
                    );
                }
            }
            QUALCOMM_CHROMA_FLASH => {
                if let Some(value) = extract_i16_value(entry, data, byte_order) {
                    tags.insert(
                        "Qualcomm:ChromaFlash".to_string(),
                        decode_chroma_flash(value),
                    );
                }
            }
            QUALCOMM_CHROMA_FLASH_FRAMES => {
                if let Some(value) = extract_i16_value(entry, data, byte_order) {
                    tags.insert("Qualcomm:ChromaFlashFrames".to_string(), value.to_string());
                }
            }
            QUALCOMM_OPTIZOOM => {
                if let Some(value) = extract_i16_value(entry, data, byte_order) {
                    tags.insert("Qualcomm:OptiZoom".to_string(), decode_optizoom(value));
                }
            }
            QUALCOMM_ZOOM_LEVEL => {
                if let Some(value) = extract_i16_value(entry, data, byte_order) {
                    tags.insert("Qualcomm:ZoomLevel".to_string(), decode_zoom_level(value));
                }
            }
            QUALCOMM_HDR_MODE => {
                if let Some(value) = extract_i16_value(entry, data, byte_order) {
                    tags.insert("Qualcomm:HDRMode".to_string(), decode_hdr_mode(value));
                }
            }
            QUALCOMM_MULTI_FRAME_NR => {
                if let Some(value) = extract_i16_value(entry, data, byte_order) {
                    let status = if value > 0 { "On" } else { "Off" };
                    tags.insert(
                        "Qualcomm:MultiFrameNoiseReduction".to_string(),
                        status.to_string(),
                    );
                }
            }
            QUALCOMM_SCENE_DETECTION => {
                if let Some(value) = extract_i16_value(entry, data, byte_order) {
                    tags.insert(
                        "Qualcomm:SceneDetection".to_string(),
                        decode_scene_type(value),
                    );
                }
            }
            QUALCOMM_BOKEH_MODE => {
                if let Some(value) = extract_i16_value(entry, data, byte_order) {
                    let status = if value > 0 { "On" } else { "Off" };
                    tags.insert("Qualcomm:BokehMode".to_string(), status.to_string());
                }
            }
            QUALCOMM_BOKEH_LEVEL => {
                if let Some(value) = extract_i16_value(entry, data, byte_order) {
                    tags.insert("Qualcomm:BokehLevel".to_string(), value.to_string());
                }
            }
            QUALCOMM_LOW_LIGHT_MODE => {
                if let Some(value) = extract_i16_value(entry, data, byte_order) {
                    let status = if value > 0 { "On" } else { "Off" };
                    tags.insert("Qualcomm:LowLightMode".to_string(), status.to_string());
                }
            }
            QUALCOMM_NIGHT_MODE => {
                if let Some(value) = extract_i16_value(entry, data, byte_order) {
                    let status = if value > 0 { "On" } else { "Off" };
                    tags.insert("Qualcomm:NightMode".to_string(), status.to_string());
                }
            }
            QUALCOMM_PHASE_DETECT_AF => {
                if let Some(value) = extract_i16_value(entry, data, byte_order) {
                    let status = if value > 0 { "Active" } else { "Inactive" };
                    tags.insert("Qualcomm:PhaseDetectAF".to_string(), status.to_string());
                }
            }
            QUALCOMM_ISP_VERSION => {
                if let Some(value) = extract_u32_value(entry, data, byte_order) {
                    tags.insert(
                        "Qualcomm:ISPVersion".to_string(),
                        format!("{}.{}", value >> 16, value & 0xFFFF),
                    );
                }
            }
            QUALCOMM_FRAME_MERGE_COUNT => {
                if let Some(value) = extract_i16_value(entry, data, byte_order) {
                    tags.insert("Qualcomm:FrameMergeCount".to_string(), value.to_string());
                }
            }
            _ => {
                // Unknown tag - skip or log for debugging
            }
        }
    }
}

impl MakerNoteParser for QualcommParser {
    fn manufacturer_name(&self) -> &'static str {
        "Qualcomm"
    }

    fn tag_prefix(&self) -> &'static str {
        "Qualcomm:"
    }

    fn parse(
        &self,
        data: &[u8],
        byte_order: ByteOrder,
        tags: &mut HashMap<String, String>,
    ) -> Result<(), String> {
        if data.len() < 8 {
            return Err("Qualcomm MakerNote data too short".to_string());
        }

        // Qualcomm MakerNotes may start with "Qualcomm" signature
        let ifd_offset = if data.len() >= 8 && &data[0..8] == QUALCOMM_SIGNATURE {
            // Skip signature and padding (usually 8-10 bytes total)
            10
        } else {
            // Assume IFD starts immediately
            0
        };

        if ifd_offset + 2 > data.len() {
            return Err("Invalid IFD offset".to_string());
        }

        // Read number of IFD entries
        let entry_count = match byte_order {
            ByteOrder::LittleEndian => u16::from_le_bytes([data[ifd_offset], data[ifd_offset + 1]]),
            ByteOrder::BigEndian => u16::from_be_bytes([data[ifd_offset], data[ifd_offset + 1]]),
        };

        if entry_count == 0 || entry_count > 500 {
            return Err(format!(
                "Invalid entry count: {} (expected 1-500)",
                entry_count
            ));
        }

        // Parse each IFD entry
        let entry_size = 12; // Standard IFD entry size
        let mut offset = ifd_offset + 2;

        for _ in 0..entry_count {
            if offset + entry_size > data.len() {
                break;
            }

            // Parse IFD entry manually
            let tag = match byte_order {
                ByteOrder::LittleEndian => u16::from_le_bytes([data[offset], data[offset + 1]]),
                ByteOrder::BigEndian => u16::from_be_bytes([data[offset], data[offset + 1]]),
            };

            let field_type = match byte_order {
                ByteOrder::LittleEndian => u16::from_le_bytes([data[offset + 2], data[offset + 3]]),
                ByteOrder::BigEndian => u16::from_be_bytes([data[offset + 2], data[offset + 3]]),
            };

            let count = match byte_order {
                ByteOrder::LittleEndian => u32::from_le_bytes([
                    data[offset + 4],
                    data[offset + 5],
                    data[offset + 6],
                    data[offset + 7],
                ]),
                ByteOrder::BigEndian => u32::from_be_bytes([
                    data[offset + 4],
                    data[offset + 5],
                    data[offset + 6],
                    data[offset + 7],
                ]),
            };

            let value_offset = match byte_order {
                ByteOrder::LittleEndian => u32::from_le_bytes([
                    data[offset + 8],
                    data[offset + 9],
                    data[offset + 10],
                    data[offset + 11],
                ]),
                ByteOrder::BigEndian => u32::from_be_bytes([
                    data[offset + 8],
                    data[offset + 9],
                    data[offset + 10],
                    data[offset + 11],
                ]),
            };

            let entry = IfdEntry {
                tag_id: tag,
                field_type,
                value_count: count,
                value_offset,
            };

            self.parse_entry(&entry, data, byte_order, tags);

            offset += entry_size;
        }

        Ok(())
    }

    fn validate_header(&self, data: &[u8]) -> bool {
        // Accept data with or without Qualcomm signature
        if data.len() >= 8 && &data[0..8] == QUALCOMM_SIGNATURE {
            return true;
        }

        // Also accept if it looks like valid IFD data
        if data.len() >= 2 {
            let entry_count = u16::from_le_bytes([data[0], data[1]]);
            if entry_count > 0 && entry_count < 500 {
                return true;
            }
        }

        false
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_decode_clear_sight() {
        assert_eq!(decode_clear_sight(0), "Off");
        assert_eq!(decode_clear_sight(1), "On");
        assert_eq!(decode_clear_sight(2), "Auto");
    }

    #[test]
    fn test_decode_clear_sight_mode() {
        assert_eq!(decode_clear_sight_mode(0), "None");
        assert_eq!(decode_clear_sight_mode(1), "Monochrome + RGB Fusion");
        assert_eq!(decode_clear_sight_mode(3), "Multi-Camera Fusion");
    }

    #[test]
    fn test_decode_chroma_flash() {
        assert_eq!(decode_chroma_flash(0), "Off");
        assert_eq!(decode_chroma_flash(1), "Flash + No Flash Blend");
    }

    #[test]
    fn test_decode_hdr_mode() {
        assert_eq!(decode_hdr_mode(0), "Off");
        assert_eq!(decode_hdr_mode(1), "HDR");
        assert_eq!(decode_hdr_mode(4), "Staggered HDR");
    }

    #[test]
    fn test_decode_scene_type() {
        assert_eq!(decode_scene_type(0), "None");
        assert_eq!(decode_scene_type(1), "Portrait");
        assert_eq!(decode_scene_type(10), "Document");
    }

    #[test]
    fn test_decode_optizoom() {
        assert_eq!(decode_optizoom(0), "Off");
        assert_eq!(decode_optizoom(2), "Medium");
        assert_eq!(decode_optizoom(4), "Maximum");
    }

    #[test]
    fn test_decode_zoom_level() {
        assert_eq!(decode_zoom_level(10), "1.0x");
        assert_eq!(decode_zoom_level(50), "5.0x");
        assert_eq!(decode_zoom_level(100), "10.0x");
    }

    #[test]
    fn test_qualcomm_parser_trait() {
        let parser = QualcommParser::new();
        assert_eq!(parser.manufacturer_name(), "Qualcomm");
        assert_eq!(parser.tag_prefix(), "Qualcomm:");
    }

    #[test]
    fn test_validate_header_with_signature() {
        let parser = QualcommParser::new();
        let mut data = Vec::new();
        data.extend_from_slice(b"Qualcomm");
        data.extend_from_slice(&[0x00, 0x00]); // Padding
        data.extend_from_slice(&[0x05, 0x00]); // 5 entries

        assert!(parser.validate_header(&data));
    }

    #[test]
    fn test_parse_clear_sight_tag() {
        let parser = QualcommParser::new();
        let mut data = Vec::new();

        // Create minimal IFD with one entry
        data.extend_from_slice(&[0x01, 0x00]); // 1 entry

        // Clear Sight tag entry (tag=0x0001, type=3 (SHORT), count=1, value=1 (On))
        data.extend_from_slice(&[0x01, 0x00]); // Tag
        data.extend_from_slice(&[0x03, 0x00]); // Type: SHORT
        data.extend_from_slice(&[0x01, 0x00, 0x00, 0x00]); // Count: 1
        data.extend_from_slice(&[0x01, 0x00, 0x00, 0x00]); // Value: 1 (inline)

        let mut tags = HashMap::new();
        let result = parser.parse(&data, ByteOrder::LittleEndian, &mut tags);

        assert!(result.is_ok());
        assert_eq!(tags.get("Qualcomm:ClearSight"), Some(&"On".to_string()));
    }
}
