//! Qualcomm MakerNote parser
//!
//! Parses Qualcomm Snapdragon camera-specific EXIF MakerNote tags containing
//! ISP (Image Signal Processor) computational photography settings and
//! Qualcomm-exclusive camera features.
//!
//! ## Supported Features
//! - Clear Sight dual-camera fusion
//! - Chroma Flash multi-frame blending
//! - OptiZoom digital zoom enhancement
//! - HDR mode settings
//! - Multi-frame noise reduction
//! - AI scene detection
//! - Bokeh depth processing
//! - Low-light enhancement
//!
//! ## Architecture
//! Qualcomm's MakerNotes are generated by the Snapdragon ISP and contain
//! metadata about computational photography features available on devices
//! using Qualcomm chipsets. These tags are manufacturer-agnostic but specific
//! to Qualcomm's camera pipeline.

#![allow(dead_code)]
#![allow(unused_imports)]

use crate::parsers::tiff::ifd_parser::{ByteOrder, IfdEntry};
use std::collections::HashMap;

use super::shared::array_extractors::extract_i16_array;
use super::shared::generic_decoders::{SimpleValueDecoder, ON_OFF};
use super::shared::MakerNoteParser;

// Qualcomm MakerNote Tag IDs
// Note: Qualcomm's tag structure is proprietary and reverse-engineered
const QUALCOMM_CLEAR_SIGHT: u16 = 0x0001; // Clear Sight fusion status
const QUALCOMM_CLEAR_SIGHT_MODE: u16 = 0x0002; // Fusion mode variant
const QUALCOMM_CHROMA_FLASH: u16 = 0x0004; // Chroma Flash status
const QUALCOMM_CHROMA_FLASH_FRAMES: u16 = 0x0005; // Number of frames used
const QUALCOMM_OPTIZOOM: u16 = 0x0007; // OptiZoom enhancement
const QUALCOMM_ZOOM_LEVEL: u16 = 0x0008; // Digital zoom level (10x = 100)
const QUALCOMM_HDR_MODE: u16 = 0x000A; // HDR processing mode
const QUALCOMM_MULTI_FRAME_NR: u16 = 0x000C; // Multi-frame noise reduction
const QUALCOMM_SCENE_DETECTION: u16 = 0x000E; // AI scene detection
const QUALCOMM_BOKEH_MODE: u16 = 0x0010; // Bokeh depth processing
const QUALCOMM_BOKEH_LEVEL: u16 = 0x0011; // Bokeh blur amount
const QUALCOMM_LOW_LIGHT_MODE: u16 = 0x0013; // Low-light enhancement
const QUALCOMM_NIGHT_MODE: u16 = 0x0015; // Night mode processing
const QUALCOMM_PHASE_DETECT_AF: u16 = 0x0017; // Phase detection AF status
const QUALCOMM_ISP_VERSION: u16 = 0x0019; // Snapdragon ISP version
const QUALCOMM_FRAME_MERGE_COUNT: u16 = 0x001B; // Merged frame count

// Qualcomm signature for validation
const QUALCOMM_SIGNATURE: &[u8] = b"Qualcomm";

// ============================================================================
// Decoders - Using Shared Utilities
// ============================================================================

/// Decoder for Clear Sight fusion status
/// Maps 0=Off, 1=On, 2=Auto
const CLEAR_SIGHT_DECODER: SimpleValueDecoder<i16> = SimpleValueDecoder::new(&[
    (0, "Off"),
    (1, "On"),
    (2, "Auto"),
]);

/// Decoder for Clear Sight fusion mode variant
/// Different types of camera fusion modes available
const CLEAR_SIGHT_MODE_DECODER: SimpleValueDecoder<i16> = SimpleValueDecoder::new(&[
    (0, "None"),
    (1, "Monochrome + RGB Fusion"),
    (2, "Wide + Telephoto Fusion"),
    (3, "Multi-Camera Fusion"),
]);

/// Decoder for Chroma Flash multi-frame blending status
/// Flash fusion techniques for improved lighting
const CHROMA_FLASH_DECODER: SimpleValueDecoder<i16> = SimpleValueDecoder::new(&[
    (0, "Off"),
    (1, "Flash + No Flash Blend"),
    (2, "Multi-Flash Blend"),
]);

/// Decoder for HDR processing mode
/// Various HDR capture and processing techniques
const HDR_MODE_DECODER: SimpleValueDecoder<i16> = SimpleValueDecoder::new(&[
    (0, "Off"),
    (1, "HDR"),
    (2, "Auto HDR"),
    (3, "HDR+"),
    (4, "Staggered HDR"),
]);

/// Decoder for AI scene detection results
/// Automatically detected scene types for optimal processing
const SCENE_TYPE_DECODER: SimpleValueDecoder<i16> = SimpleValueDecoder::new(&[
    (0, "None"),
    (1, "Portrait"),
    (2, "Landscape"),
    (3, "Food"),
    (4, "Night"),
    (5, "Sunset"),
    (6, "Beach"),
    (7, "Snow"),
    (8, "Flower"),
    (9, "Pet"),
    (10, "Document"),
]);

/// Decoder for OptiZoom enhancement level
/// Digital zoom quality enhancement levels
const OPTIZOOM_DECODER: SimpleValueDecoder<i16> = SimpleValueDecoder::new(&[
    (0, "Off"),
    (1, "Low"),
    (2, "Medium"),
    (3, "High"),
    (4, "Maximum"),
]);

/// Decodes zoom level from encoded value
///
/// # Arguments
/// * `value` - Zoom level (10 = 1.0x, 100 = 10.0x)
///
/// # Returns
/// Human-readable zoom level with 'x' suffix
///
/// # Encoding
/// The zoom level is encoded as value/10, so:
/// - 10 = 1.0x
/// - 25 = 2.5x
/// - 100 = 10.0x
fn decode_zoom_level(value: i16) -> String {
    if value <= 0 {
        return "1.0x".to_string();
    }
    let zoom = value as f32 / 10.0;
    format!("{:.1}x", zoom)
}

/// Extracts a 16-bit signed value from IFD entry
///
/// # Arguments
/// * `entry` - IFD entry containing the value
/// * `_data` - Full MakerNote data buffer (unused for inline values)
/// * `byte_order` - Byte order for parsing multi-byte values
///
/// # Returns
/// Extracted value or None if invalid
///
/// # Implementation Notes
/// For SHORT type with count=1, the value is stored inline in the value_offset field.
/// The byte order determines which 16 bits of the 32-bit value_offset to use.
fn extract_i16_value(entry: &IfdEntry, _data: &[u8], byte_order: ByteOrder) -> Option<i16> {
    if entry.value_count != 1 {
        return None;
    }

    // For SHORT type (count=1), value is inline in value_offset field
    // Little endian: use lower 16 bits
    // Big endian: use upper 16 bits
    let value = match byte_order {
        ByteOrder::LittleEndian => (entry.value_offset & 0xFFFF) as i16,
        ByteOrder::BigEndian => ((entry.value_offset >> 16) & 0xFFFF) as i16,
    };

    Some(value)
}

/// Extracts a 32-bit unsigned value from IFD entry
///
/// # Arguments
/// * `entry` - IFD entry containing the value
/// * `_data` - Full MakerNote data buffer (unused for inline values)
/// * `_byte_order` - Byte order (unused as value_offset is already parsed)
///
/// # Returns
/// Extracted value or None if invalid
///
/// # Implementation Notes
/// For LONG type with count=1, the entire value_offset field is the value.
fn extract_u32_value(entry: &IfdEntry, _data: &[u8], _byte_order: ByteOrder) -> Option<u32> {
    if entry.value_count != 1 {
        return None;
    }

    Some(entry.value_offset)
}

/// Qualcomm MakerNote parser implementation
pub struct QualcommParser;

impl Default for QualcommParser {
    fn default() -> Self {
        Self::new()
    }
}

impl QualcommParser {
    /// Creates a new Qualcomm parser instance
    pub fn new() -> Self {
        QualcommParser
    }

    /// Parse a single IFD entry and extract tag value
    ///
    /// # Arguments
    /// * `entry` - IFD entry to parse
    /// * `data` - Full MakerNote data buffer
    /// * `byte_order` - Byte order for multi-byte values
    /// * `tags` - HashMap to insert extracted tags into
    ///
    /// # Implementation Strategy
    /// Uses shared decoders for common patterns (On/Off, match-based)
    /// and custom logic only for unique transformations (zoom level, ISP version)
    fn parse_entry(
        &self,
        entry: &IfdEntry,
        data: &[u8],
        byte_order: ByteOrder,
        tags: &mut HashMap<String, String>,
    ) {
        let tag_id = entry.tag_id;

        match tag_id {
            // Clear Sight dual-camera fusion
            QUALCOMM_CLEAR_SIGHT => {
                if let Some(value) = extract_i16_value(entry, data, byte_order) {
                    tags.insert("Qualcomm:ClearSight".to_string(), CLEAR_SIGHT_DECODER.decode(value));
                }
            }
            QUALCOMM_CLEAR_SIGHT_MODE => {
                if let Some(value) = extract_i16_value(entry, data, byte_order) {
                    tags.insert(
                        "Qualcomm:ClearSightMode".to_string(),
                        CLEAR_SIGHT_MODE_DECODER.decode(value),
                    );
                }
            }

            // Chroma Flash multi-frame blending
            QUALCOMM_CHROMA_FLASH => {
                if let Some(value) = extract_i16_value(entry, data, byte_order) {
                    tags.insert(
                        "Qualcomm:ChromaFlash".to_string(),
                        CHROMA_FLASH_DECODER.decode(value),
                    );
                }
            }
            QUALCOMM_CHROMA_FLASH_FRAMES => {
                if let Some(value) = extract_i16_value(entry, data, byte_order) {
                    tags.insert("Qualcomm:ChromaFlashFrames".to_string(), value.to_string());
                }
            }

            // OptiZoom digital enhancement
            QUALCOMM_OPTIZOOM => {
                if let Some(value) = extract_i16_value(entry, data, byte_order) {
                    tags.insert("Qualcomm:OptiZoom".to_string(), OPTIZOOM_DECODER.decode(value));
                }
            }
            QUALCOMM_ZOOM_LEVEL => {
                if let Some(value) = extract_i16_value(entry, data, byte_order) {
                    tags.insert("Qualcomm:ZoomLevel".to_string(), decode_zoom_level(value));
                }
            }

            // HDR processing
            QUALCOMM_HDR_MODE => {
                if let Some(value) = extract_i16_value(entry, data, byte_order) {
                    tags.insert("Qualcomm:HDRMode".to_string(), HDR_MODE_DECODER.decode(value));
                }
            }

            // Multi-frame noise reduction (binary On/Off)
            QUALCOMM_MULTI_FRAME_NR => {
                if let Some(value) = extract_i16_value(entry, data, byte_order) {
                    // Normalize to 0/1 for ON_OFF decoder
                    let normalized = if value > 0 { 1 } else { 0 };
                    tags.insert(
                        "Qualcomm:MultiFrameNoiseReduction".to_string(),
                        ON_OFF.decode(normalized),
                    );
                }
            }

            // AI scene detection
            QUALCOMM_SCENE_DETECTION => {
                if let Some(value) = extract_i16_value(entry, data, byte_order) {
                    tags.insert(
                        "Qualcomm:SceneDetection".to_string(),
                        SCENE_TYPE_DECODER.decode(value),
                    );
                }
            }

            // Bokeh depth processing (binary On/Off)
            QUALCOMM_BOKEH_MODE => {
                if let Some(value) = extract_i16_value(entry, data, byte_order) {
                    let normalized = if value > 0 { 1 } else { 0 };
                    tags.insert("Qualcomm:BokehMode".to_string(), ON_OFF.decode(normalized));
                }
            }
            QUALCOMM_BOKEH_LEVEL => {
                if let Some(value) = extract_i16_value(entry, data, byte_order) {
                    tags.insert("Qualcomm:BokehLevel".to_string(), value.to_string());
                }
            }

            // Low-light enhancement (binary On/Off)
            QUALCOMM_LOW_LIGHT_MODE => {
                if let Some(value) = extract_i16_value(entry, data, byte_order) {
                    let normalized = if value > 0 { 1 } else { 0 };
                    tags.insert("Qualcomm:LowLightMode".to_string(), ON_OFF.decode(normalized));
                }
            }

            // Night mode processing (binary On/Off)
            QUALCOMM_NIGHT_MODE => {
                if let Some(value) = extract_i16_value(entry, data, byte_order) {
                    let normalized = if value > 0 { 1 } else { 0 };
                    tags.insert("Qualcomm:NightMode".to_string(), ON_OFF.decode(normalized));
                }
            }

            // Phase detection autofocus (Active/Inactive)
            QUALCOMM_PHASE_DETECT_AF => {
                if let Some(value) = extract_i16_value(entry, data, byte_order) {
                    let status = if value > 0 { "Active" } else { "Inactive" };
                    tags.insert("Qualcomm:PhaseDetectAF".to_string(), status.to_string());
                }
            }

            // ISP version (major.minor format from u32)
            QUALCOMM_ISP_VERSION => {
                if let Some(value) = extract_u32_value(entry, data, byte_order) {
                    // Upper 16 bits = major version, lower 16 bits = minor version
                    tags.insert(
                        "Qualcomm:ISPVersion".to_string(),
                        format!("{}.{}", value >> 16, value & 0xFFFF),
                    );
                }
            }

            // Frame merge count (raw numeric value)
            QUALCOMM_FRAME_MERGE_COUNT => {
                if let Some(value) = extract_i16_value(entry, data, byte_order) {
                    tags.insert("Qualcomm:FrameMergeCount".to_string(), value.to_string());
                }
            }

            _ => {
                // Unknown tag - skip silently for forward compatibility
            }
        }
    }
}

impl MakerNoteParser for QualcommParser {
    fn manufacturer_name(&self) -> &'static str {
        "Qualcomm"
    }

    fn tag_prefix(&self) -> &'static str {
        "Qualcomm:"
    }

    fn parse(
        &self,
        data: &[u8],
        byte_order: ByteOrder,
        tags: &mut HashMap<String, String>,
    ) -> Result<(), String> {
        if data.len() < 8 {
            return Err("Qualcomm MakerNote data too short".to_string());
        }

        // Qualcomm MakerNotes may start with "Qualcomm" signature
        // If present, skip it to find the IFD start
        let ifd_offset = if data.len() >= 8 && &data[0..8] == QUALCOMM_SIGNATURE {
            // Skip signature and padding (usually 8-10 bytes total)
            10
        } else {
            // Assume IFD starts immediately
            0
        };

        if ifd_offset + 2 > data.len() {
            return Err("Invalid IFD offset".to_string());
        }

        // Read number of IFD entries (2 bytes at IFD start)
        let entry_count = match byte_order {
            ByteOrder::LittleEndian => u16::from_le_bytes([data[ifd_offset], data[ifd_offset + 1]]),
            ByteOrder::BigEndian => u16::from_be_bytes([data[ifd_offset], data[ifd_offset + 1]]),
        };

        // Sanity check: entry count should be reasonable
        if entry_count == 0 || entry_count > 500 {
            return Err(format!(
                "Invalid entry count: {} (expected 1-500)",
                entry_count
            ));
        }

        // Parse each IFD entry (12 bytes each)
        let entry_size = 12; // Standard IFD entry size
        let mut offset = ifd_offset + 2;

        for _ in 0..entry_count {
            if offset + entry_size > data.len() {
                break; // Incomplete entry, stop parsing
            }

            // Parse IFD entry manually from raw bytes
            // Format: [tag:2][type:2][count:4][value_offset:4]
            let tag = match byte_order {
                ByteOrder::LittleEndian => u16::from_le_bytes([data[offset], data[offset + 1]]),
                ByteOrder::BigEndian => u16::from_be_bytes([data[offset], data[offset + 1]]),
            };

            let field_type = match byte_order {
                ByteOrder::LittleEndian => u16::from_le_bytes([data[offset + 2], data[offset + 3]]),
                ByteOrder::BigEndian => u16::from_be_bytes([data[offset + 2], data[offset + 3]]),
            };

            let count = match byte_order {
                ByteOrder::LittleEndian => u32::from_le_bytes([
                    data[offset + 4],
                    data[offset + 5],
                    data[offset + 6],
                    data[offset + 7],
                ]),
                ByteOrder::BigEndian => u32::from_be_bytes([
                    data[offset + 4],
                    data[offset + 5],
                    data[offset + 6],
                    data[offset + 7],
                ]),
            };

            let value_offset = match byte_order {
                ByteOrder::LittleEndian => u32::from_le_bytes([
                    data[offset + 8],
                    data[offset + 9],
                    data[offset + 10],
                    data[offset + 11],
                ]),
                ByteOrder::BigEndian => u32::from_be_bytes([
                    data[offset + 8],
                    data[offset + 9],
                    data[offset + 10],
                    data[offset + 11],
                ]),
            };

            // Create IFD entry structure
            let entry = IfdEntry {
                tag_id: tag,
                field_type,
                value_count: count,
                value_offset,
            };

            // Parse this entry's tag value
            self.parse_entry(&entry, data, byte_order, tags);

            offset += entry_size;
        }

        Ok(())
    }

    fn validate_header(&self, data: &[u8]) -> bool {
        // Accept data with Qualcomm signature
        if data.len() >= 8 && &data[0..8] == QUALCOMM_SIGNATURE {
            return true;
        }

        // Also accept if it looks like valid IFD data (reasonable entry count)
        if data.len() >= 2 {
            let entry_count = u16::from_le_bytes([data[0], data[1]]);
            if entry_count > 0 && entry_count < 500 {
                return true;
            }
        }

        false
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_clear_sight_decoder() {
        assert_eq!(CLEAR_SIGHT_DECODER.decode(0), "Off");
        assert_eq!(CLEAR_SIGHT_DECODER.decode(1), "On");
        assert_eq!(CLEAR_SIGHT_DECODER.decode(2), "Auto");
    }

    #[test]
    fn test_clear_sight_mode_decoder() {
        assert_eq!(CLEAR_SIGHT_MODE_DECODER.decode(0), "None");
        assert_eq!(CLEAR_SIGHT_MODE_DECODER.decode(1), "Monochrome + RGB Fusion");
        assert_eq!(CLEAR_SIGHT_MODE_DECODER.decode(3), "Multi-Camera Fusion");
    }

    #[test]
    fn test_chroma_flash_decoder() {
        assert_eq!(CHROMA_FLASH_DECODER.decode(0), "Off");
        assert_eq!(CHROMA_FLASH_DECODER.decode(1), "Flash + No Flash Blend");
    }

    #[test]
    fn test_hdr_mode_decoder() {
        assert_eq!(HDR_MODE_DECODER.decode(0), "Off");
        assert_eq!(HDR_MODE_DECODER.decode(1), "HDR");
        assert_eq!(HDR_MODE_DECODER.decode(4), "Staggered HDR");
    }

    #[test]
    fn test_scene_type_decoder() {
        assert_eq!(SCENE_TYPE_DECODER.decode(0), "None");
        assert_eq!(SCENE_TYPE_DECODER.decode(1), "Portrait");
        assert_eq!(SCENE_TYPE_DECODER.decode(10), "Document");
    }

    #[test]
    fn test_optizoom_decoder() {
        assert_eq!(OPTIZOOM_DECODER.decode(0), "Off");
        assert_eq!(OPTIZOOM_DECODER.decode(2), "Medium");
        assert_eq!(OPTIZOOM_DECODER.decode(4), "Maximum");
    }

    #[test]
    fn test_decode_zoom_level() {
        assert_eq!(decode_zoom_level(10), "1.0x");
        assert_eq!(decode_zoom_level(50), "5.0x");
        assert_eq!(decode_zoom_level(100), "10.0x");
    }

    #[test]
    fn test_on_off_decoder() {
        // Test the shared ON_OFF decoder
        assert_eq!(ON_OFF.decode(0), "Off");
        assert_eq!(ON_OFF.decode(1), "On");
    }

    #[test]
    fn test_qualcomm_parser_trait() {
        let parser = QualcommParser::new();
        assert_eq!(parser.manufacturer_name(), "Qualcomm");
        assert_eq!(parser.tag_prefix(), "Qualcomm:");
    }

    #[test]
    fn test_validate_header_with_signature() {
        let parser = QualcommParser::new();
        let mut data = Vec::new();
        data.extend_from_slice(b"Qualcomm");
        data.extend_from_slice(&[0x00, 0x00]); // Padding
        data.extend_from_slice(&[0x05, 0x00]); // 5 entries

        assert!(parser.validate_header(&data));
    }

    #[test]
    fn test_parse_clear_sight_tag() {
        let parser = QualcommParser::new();
        let mut data = Vec::new();

        // Create minimal IFD with one entry
        data.extend_from_slice(&[0x01, 0x00]); // 1 entry

        // Clear Sight tag entry (tag=0x0001, type=3 (SHORT), count=1, value=1 (On))
        data.extend_from_slice(&[0x01, 0x00]); // Tag
        data.extend_from_slice(&[0x03, 0x00]); // Type: SHORT
        data.extend_from_slice(&[0x01, 0x00, 0x00, 0x00]); // Count: 1
        data.extend_from_slice(&[0x01, 0x00, 0x00, 0x00]); // Value: 1 (inline)

        let mut tags = HashMap::new();
        let result = parser.parse(&data, ByteOrder::LittleEndian, &mut tags);

        assert!(result.is_ok());
        assert_eq!(tags.get("Qualcomm:ClearSight"), Some(&"On".to_string()));
    }
}
