//! Legacy stub for generated tag database
//!
//! THIS FILE IS AUTO-GENERATED BY build.rs
//! Tag data is now in YAML files in domain crates.
//!
//! Generated from ExifTool: https://github.com/exiftool/exiftool
//! Total tags: 32677

#![allow(dead_code)]

use crate::core::TagDescriptor;

/// Legacy lookup function (now delegates to manual registry)
pub fn get_generated_tag_descriptor(name: &str) -> Option<&TagDescriptor> {
    crate::tag_db::tag_registry::get_tag_descriptor(name)
}

/// Returns the total number of tags (from ExifTool parse)
pub fn generated_tag_count() -> usize {
    32677
}
