#!/usr/bin/env -S uv run
# /// script
# requires-python = ">=3.9"
# dependencies = []
# ///
"""Generate JPEG tag support reports from jpeg_tag_matrix.py results.

Inputs:  <TAGMATRIX_WORK>/results.json  (+ readonly manifest if present)
Outputs: docs/reference/jpeg-tag-support.md   (supported-tag mapping)
         docs/reference/jpeg-tag-matrix.md    (full classification matrix + bugs)
"""

import argparse
import json
import os
import sys
import tempfile
from collections import Counter, defaultdict
from datetime import datetime
from pathlib import Path

WORK = Path(os.environ.get("TAGMATRIX_WORK")
           or (Path(tempfile.gettempdir()) / "oxidex-tagmap"))
REPO = Path(__file__).resolve().parent.parent
RESULTS = WORK / "results.json"
READONLY = WORK / "exiftool_jpeg_readonly_tags.json"
OUT_SUPPORT = REPO / "docs/reference/jpeg-tag-support.md"
OUT_MATRIX = REPO / "docs/reference/jpeg-tag-matrix.md"
BASELINE = REPO / "docs/reference/jpeg-tag-baseline.json"

READ_OKISH = {"OK", "MISMATCH_FORMAT"}

READ_BUG_LABELS = {
    "R-iptc-binary-garbage": "IPTC binary int16u decoded as NUL-garbage string",
    "R-binary-garbage": "binary value decoded as NUL-garbage string",
    "R-apex-missing": "APEX ValueConv (2^x) not applied",
    "R-namespace-blind-printconv": "-e compat applies EXIF enum table to XMP tag",
    "R-acr-prefix": 'ACR "TagName: " ValueConv prefix not stripped',
    "R-undef-not-decoded": "undef/binary value shown as opaque (Binary, N bytes)",
    "R-utf16-not-decoded": "XP* UTF-16 string shown as raw integer",
    "R-float-raw-bits": "float value shown as raw IEEE-754 bits",
    "R-xmp-struct-concat": "XMP struct fields concatenated into garbage scalar",
}
WRITE_BUG_LABELS = {
    "I1-no-printconvinv": "PrintConvInv missing: human-readable stored as raw",
    "I2-wrong-type-enum": "written as ASCII where SHORT/LONG expected",
    "I3-wrong-type-numeric": "written as ASCII where numeric/rational expected",
    "I4-wrong-type-undef": "written as ASCII where UNDEF expected (+NUL)",
    "I5-subdir-poison": "junk written into subdirectory pointer tag",
    "R4-registry-asymmetry": "writes OK; reads back under hex key (registry asymmetry)",
}


def classify(r):
    """Roll a result up into (headline, read-desc, write-desc)."""
    rd, wr = r.get("read"), r.get("write")
    detail = (r.get("detail") or "").lower()

    if wr == "OK":
        wr_c = "✅ ok"
        if r.get("write_quality") == "nonstandard":
            wr_c = "⚠️ writes, but non-standard encoding (exiftool tolerates)"
        if r.get("bug_cluster") == "R4-registry-asymmetry":
            wr_c = "✅ ok (reads back under hex key)"
    elif wr == "ERROR":
        if "type mismatch" in detail:
            wr_c = "🐛 broken: type-validation rejects CLI string values"
        elif "shift dates" in detail:
            wr_c = "🐛 broken: datetime write misrouted to date-shift path"
        else:
            wr_c = "🐛 broken: error"
    elif wr == "INTEROP_BROKEN":
        wr_c = "🐛 broken: " + WRITE_BUG_LABELS.get(r.get("bug_cluster"),
                                                    "interop (exiftool can't read it)")
    elif wr == "NOT_WRITTEN":
        wr_c = "— unsupported (silent no-op)"
    else:
        wr_c = f"{str(wr).lower()}"

    if rd == "OK":
        rd_c = "✅ ok"
    elif rd == "MISMATCH_FORMAT":
        rd_c = "✅ ok (formatting differs from exiftool)"
    elif rd == "MISMATCH":
        rd_c = "🐛 broken: " + READ_BUG_LABELS.get(r.get("read_bug"),
                                                   "wrong value decoded")
    elif rd == "MISSING":
        rd_c = "— unsupported"
    elif rd == "NO_SAMPLE":
        rd_c = "❔ untestable (exiftool could not synthesize a sample)"
    else:
        rd_c = f"{str(rd).lower()}"

    if rd in READ_OKISH and wr == "OK":
        head = ("⚠️ Full (write non-standard encoding)"
                if r.get("write_quality") == "nonstandard"
                else "✅ Full (read + write)")
    elif rd in READ_OKISH and wr in ("ERROR", "INTEROP_BROKEN"):
        head = "🐛 Read OK, write broken"
    elif rd in READ_OKISH:
        head = "📖 Read only"
    elif rd == "MISMATCH":
        head = "🐛 Read broken"
    elif wr == "OK":
        head = "✍️ Write only"
    elif rd == "NO_SAMPLE":
        head = "❔ Untestable"
    else:
        head = "❌ Unsupported"
    return head, rd_c, wr_c


def md_escape(s, n=90):
    return str(s).replace("|", "\\|").replace("\n", " ")[:n]


def autogen_callout():
    """VitePress info callout matching the site's auto-generated page style."""
    today = datetime.now().strftime("%Y-%m-%d")
    ver = "ExifTool"
    manifest = WORK / "exiftool_jpeg_tags.json"
    if manifest.exists():
        try:
            ver = json.loads(manifest.read_text()).get("generated_by", ver)
        except json.JSONDecodeError:
            pass  # malformed manifest; keep the generic "ExifTool" fallback
    return (
        "::: info Auto-Generated\n"
        "This report is regenerated by the "
        "[JPEG Tag Matrix workflow]"
        "(https://github.com/swack-tools/oxidex/actions/workflows/"
        "jpeg-tag-matrix.yml) "
        f"(`scripts/jpeg_tag_matrix.py`) against **{ver}**. "
        f"Last updated: **{today}**\n"
        ":::\n")


KNOWN_BUGS = """
## Known bugs (empirically confirmed, with root cause)

All were reproduced with the release binary against exiftool 13.55; file:line
references are into this repo.

### Write path

| # | Bug | Impact (tags) | Root cause |
|---|---|---|---|
| W1 | CLI cannot write any non-String EXIF tag: values reach the writer as `TagValue::String` and strict type validation rejects them ("Type mismatch: expected Integer/Rational/... but got String") | 191 | `src/main.rs:146` wraps all CLI values as strings; `src/core/validation.rs:109`. A fix exists on the `fix/wiring` branch (commit `2433c79`) but is not on this branch |
| W2 | Datetime tags cannot be *created* on a JPEG with no pre-existing value for that tag: `-ExifIFD:DateTimeOriginal=...` is misrouted to the date-*shift* path (`src/core/date_shift.rs`), which requires a matching tag to already exist ("No date/time tags matching ... found in EXIF data" otherwise). This is what the empirical matrix measures, since the base fixture has no pre-existing date tags. **Update-in-place now works** (fixed by [#18](https://github.com/swack-tools/oxidex/pull/18)): `-ExifIFD:DateTimeOriginal=...` against a file that already has the tag set succeeds and round-trips correctly through both oxidex and exiftool | 82 (fresh-creation case only) | `src/cli/args.rs` `parse_date_shift` treats any `date/time`-named tag with a `Y:M:D H:M:S`-shaped value as a shift; the shift path itself only rewrites existing entries |
| W3 | Silent no-op with false success: XMP, IPTC, JFIF, Photoshop, Comment, InteropIFD and bare tag names are dropped, yet the CLI prints "1 image files updated" and rewrites the file | ~4,300 (incl. 1,297 readable tags) | `src/writers/tiff_writer/tiff/validator.rs:110` `separate_by_ifd` routes only IFD0/IFD1/ExifIFD/GPS/EXIF; `ifd_builder.rs:93` skips silently; `src/main.rs:175` unconditional success message |
| W4 | Type-blind serialization: registry-unknown tags are written as TIFF ASCII regardless of expected SHORT/LONG/RATIONAL/UNDEF type — produces non-standard files (`exiftool -validate` flags every one) | 32 | `src/writers/tiff_writer/tiff/ifd_entry.rs:95` picks TIFF type from the Rust value variant, never from the tag's spec |
| W5 | No PrintConv inversion: human-readable values stored raw (e.g. `GPSSpeedRef=km/h` stores "km/h" instead of "K"; exiftool then reads "Unknown (km/h)") | 8 | no inverse-conversion layer exists (`src/core/operations.rs:291` inserts CLI strings untouched) |
| W6 | Subdirectory-pointer poisoning: writing text into pointer tags (CurrentICCProfile, AsShotICCProfile, ...) corrupts downstream parsing ("Bad length ICC_Profile" on every later read) | 7 | `validator.rs:48` checks only family + numeric ID, not writability/subdirectory flags |
| W7 | Every write flips EXIF byte order MM→II (big- to little-endian) even when only one tag changes | all writes | EXIF segment fully rebuilt by `src/writers/tiff_writer/mod.rs` in II order |
| W8 | Write/read registry asymmetry: `IFD0:TargetPrinter` writes correctly but reads back as `IFD0:0x0151` | ≥1 | write resolves via manual `TAG_REGISTRY` (`src/tag_db/tag_registry.rs:1281`), read via YAML `TAG_ID_TO_NAME_INDEX` (`src/tag_db/mod.rs:302`) which lacks the ID |
| W9 | Some write errors print `Error: ...` but exit 0 (e.g. GPS rational type mismatch) — scripts can't trust the exit code | — | inconsistent error propagation in `src/main.rs` write handling |
| W10 | 57 of the 122 "successful" CLI writes actually serialize a non-standard encoding (string where numeric expected, wrong count) that exiftool tolerates on read but `-validate` flags — same root cause as W4 | 57 | `src/writers/tiff_writer/tiff/ifd_entry.rs:95` |
| W11 | Creating a GPS IFD does not add the mandatory `GPSVersionID` tag (exiftool adds it automatically) — `exiftool -validate` flags every oxidex-created GPS IFD | GPS writes | GPS IFD builder in `src/writers/tiff_writer/` has no mandatory-tag logic |

### Read path

| # | Bug | Impact (tags) | Root cause |
|---|---|---|---|
| R1 | One malformed IFD entry silently discards the **entire EXIF block** (IFD0 + ExifIFD + GPS). Trigger found in the wild: exiftool 13.55 itself writes `IFD0:GeoTiffDoubleParams` with a bad offset | whole file | `src/parsers/tiff/ifd_parser.rs:274` aborts `parse_ifd` on one bad entry; `src/core/jpeg_helpers.rs:161` swallows the error (`if let Ok`) |
| R2 | IPTC binary int16u datasets (FileFormat, FileVersion, ARMIdentifier, ARMVersion, ObjectPreviewFileFormat) decoded as strings → NUL-byte garbage | 5 | `src/parsers/jpeg/iptc_parser.rs:330-374`; a correct `parse_binary_u16` exists in `iptc_record1.rs:383` but isn't on the live path |
| R3 | `-e` compat mode applies EXIF enum tables to XMP tags by bare name (namespace-blind): e.g. XMP-exif:SensingMethod `1` renders "Not defined" instead of "Monochrome area"; plain `-j` output is correct | 7 | `src/core/exiftool_compat.rs:172` strips the group before enum lookup |
| R4 | APEX conversion missing: ApertureValue/MaxApertureValue/ShutterSpeedValue show the raw APEX number (or raw rational for XMP) instead of `2^(v/2)` / `2^(-v)` | 6 | no APEX code anywhere (`src/core/value_formatter.rs:425` only divides num/den) |
| R5 | XMP struct properties concatenated into a single garbage scalar (e.g. Flash → "TrueTrue0True0"), flattened child tags dropped | 4+ | `src/parsers/xmp/rdf_parser.rs:181-191` appends nested text nodes without separators |
| R6 | ACR-style `"TagName: value"` ValueConv prefix not stripped (Brightness, Shadows, ...) | 6+ | no equivalent of exiftool's ValueConv for these tags |
| R7 | undef values undecoded: FileSource shows "(Binary, 1 bytes)" instead of "Film Scanner"; GPSAreaInformation opaque; XP* Windows tags show raw integers instead of UTF-16 text; float-typed DNG tags show raw IEEE-754 bits (e.g. 1069547520 for 1.5) | 24 | `src/core/exiftool_compat.rs:435` (FileSource requires as_integer), no UTF-16/float decode paths |
| R8 | **Fixed by [#22](https://github.com/swack-tools/oxidex/pull/22).** Previously: JPEG COM comment, SPIFF and DQT-quality parsers existed but were never invoked from `parse_jpeg_metadata`, and multi-chunk ICC profiles were dropped with a warning. COM comment reading is now verified working (`File:Comment` reads correctly); SPIFF, DQT-derived quality, multi-chunk ICC, and APP6/GoPro are also wired in per #22 but aren't ExifTool-writable tags (or fall outside the EXIF/XMP/IPTC/JFIF/Photoshop/ICC_Profile groups this matrix synthesizes samples for), so this empirical harness can't independently confirm them | Comment (confirmed); SPIFF/DQT/ICC/APP6 (out of this harness's testable scope) | was `src/core/operations.rs:483-497`; see #22 for the fix |
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--update-baseline", action="store_true",
                    help=f"write current summary counts to {BASELINE.name}")
    ap.add_argument("--check-baseline", action="store_true",
                    help="exit 1 if support regressed vs the committed baseline")
    args = ap.parse_args()

    results = json.loads(RESULTS.read_text())
    rows = []
    for key, r in results.items():
        head, rd_c, wr_c = classify(r)
        rows.append({
            "key": key, "group": r.get("group", key.split(":")[0]),
            "name": r.get("name", key.split(":")[-1]),
            "sample": r.get("sample", ""), "type": r.get("type", ""),
            "head": head, "rd": rd_c, "wr": wr_c,
            "ox_key": r.get("ox_key", ""), "wkey": r.get("wkey", ""),
            "raw_read": r.get("read"), "raw_write": r.get("write"),
            "wq": r.get("write_quality"),
        })
    rows.sort(key=lambda x: (x["group"], x["name"]))

    heads = Counter(x["head"] for x in rows)
    by_group = defaultdict(list)
    for x in rows:
        by_group[x["group"]].append(x)

    # ---------------------------------------------------- supported mapping doc
    md = ["# JPEG Tag Support\n",
          autogen_callout(),
          ("Empirical OxiDex ↔ ExifTool tag mapping for JPEG: for each tag, "
           + "ExifTool writes a sample into a clean JPEG and `oxidex -j -e` "
           + "must read it back; writability additionally requires "
           + "`oxidex -KEY=VALUE` to round-trip through both OxiDex and "
           + "ExifTool.\n"),
          ("Only tags OxiDex can **read** from JPEG are listed here "
           + "(including those whose value formatting differs from "
           + "ExifTool). The full classification of all tested tags — "
           + "including unsupported and broken ones — is in the "
           + "[JPEG Tag Matrix](/reference/jpeg-tag-matrix). See also "
           + "[ExifTool Coverage](/reference/tag-coverage-analysis) for the "
           + "tag-database view and the "
           + "[Compatibility overview](/reference/comparison/) for "
           + "fixture-based comparisons across formats.\n")]
    n_read = sum(1 for x in rows if x["raw_read"] in READ_OKISH)
    n_write = sum(1 for x in rows if x["raw_write"] == "OK")
    md.append(f"\n**{n_read}** ExifTool tags readable, **{n_write}** writable "
              f"via the CLI (of {len(rows)} ExifTool-writable JPEG tags tested).\n")
    for g in sorted(by_group):
        sup = [x for x in by_group[g] if x["raw_read"] in READ_OKISH]
        if not sup:
            continue
        md.append(f"\n## {g} ({len(sup)} readable tags)\n")
        md.append("| ExifTool tag | OxiDex key | OxiDex write | Example value |")
        md.append("|---|---|---|---|")
        for x in sup:
            if x["raw_write"] == "OK":
                mark = "⚠️" if x.get("wq") == "nonstandard" else "✅"
                wr = f"{mark} `-{x['wkey']}=`"
            else:
                wr = "—"
            note = " *" if x["raw_read"] == "MISMATCH_FORMAT" else ""
            md.append(f"| `{x['key']}` | `{x['ox_key'] or x['key']}`{note} | {wr} "
                      f"| `{md_escape(x['sample'], 60)}` |")
    md.append("\n\\* value formatting differs from ExifTool "
              "(same underlying value, missing PrintConv).\n")
    OUT_SUPPORT.write_text("\n".join(md) + "\n")

    # ------------------------------------------------------- full matrix doc
    md = ["---", "outline: 2", "---\n",
          "# JPEG Tag Matrix\n",
          autogen_callout(),
          ("Every ExifTool-writable JPEG tag, classified by empirical test: "
           + "read support (ExifTool writes → OxiDex reads), write support "
           + "(OxiDex writes → both read back), and known bugs with root "
           + "causes. Readable tags with their working write keys are "
           + "summarized in "
           + "[JPEG Tag Support](/reference/jpeg-tag-support).\n"),
          "\n## Summary\n", "| Classification | Tags |", "|---|---|"]
    for h, n in heads.most_common():
        md.append(f"| {h} | {n} |")
    ro = []
    if READONLY.exists():
        ro = json.loads(READONLY.read_text()).get("tags", [])
        md.append(f"| 🚫 Not writable in ExifTool (no synthetic sample possible; "
                  f"untested) | {len(ro)} |")

    md.append("\n## Per-group breakdown\n")
    md.append("| Group | Full | Read-only | Write-broken | Read-broken "
              "| Write-only | Unsupported | Untestable | Total |")
    md.append("|---|---|---|---|---|---|---|---|---|")
    for g in sorted(by_group):
        c = Counter(x["head"] for x in by_group[g])
        md.append(f"| {g} | {c.get('✅ Full (read + write)', 0)} "
                  f"| {c.get('📖 Read only', 0)} "
                  f"| {c.get('🐛 Read OK, write broken', 0)} "
                  f"| {c.get('🐛 Read broken', 0)} "
                  f"| {c.get('✍️ Write only', 0)} "
                  f"| {c.get('❌ Unsupported', 0)} "
                  f"| {c.get('❔ Untestable', 0)} "
                  f"| {len(by_group[g])} |")

    md.append(KNOWN_BUGS)

    md.append("\n## Full matrix\n")
    for g in sorted(by_group):
        md.append(f"\n### {g}\n")
        md.append("| ExifTool tag | Read | Write | Example |")
        md.append("|---|---|---|---|")
        for x in by_group[g]:
            md.append(f"| `{x['name']}` | {x['rd']} | {x['wr']} "
                      f"| `{md_escape(x['sample'], 60)}` |")
    if ro:
        md.append("\n### Not writable in ExifTool (read-only universe, untested)\n")
        md.append("These exist in JPEG-relevant groups but ExifTool itself cannot "
                  "write them, so no synthetic test file could be produced.\n")
        by_g = defaultdict(list)
        for t in ro:
            by_g[t["group"]].append(t["name"])
        for g in sorted(by_g):
            names = ", ".join(f"`{n}`" for n in sorted(by_g[g])[:40])
            extra = f" … +{len(by_g[g]) - 40} more" if len(by_g[g]) > 40 else ""
            md.append(f"- **{g}** ({len(by_g[g])}): {names}{extra}")
    OUT_MATRIX.write_text("\n".join(md) + "\n")

    print(f"Wrote {OUT_SUPPORT}\nWrote {OUT_MATRIX}\n")
    for h, n in heads.most_common():
        print(f"  {h}: {n}")

    # ------------------------------------------------------ baseline handling
    counts = {
        "total_tested": len(rows),
        "readable": n_read,
        "writable_cli": n_write,
        "full": heads.get("✅ Full (read + write)", 0),
        "full_nonstandard": heads.get("⚠️ Full (write non-standard encoding)", 0),
        "read_only": heads.get("📖 Read only", 0),
        "read_broken": heads.get("🐛 Read broken", 0),
        "write_broken": heads.get("🐛 Read OK, write broken", 0),
        "unsupported": heads.get("❌ Unsupported", 0),
        "untestable": heads.get("❔ Untestable", 0),
    }
    if args.update_baseline:
        BASELINE.write_text(json.dumps(counts, indent=1) + "\n")
        print(f"Baseline updated: {BASELINE}")
    if args.check_baseline:
        if not BASELINE.exists():
            print("No baseline committed yet; skipping check")
            return
        base = json.loads(BASELINE.read_text())
        # must-not-decrease / must-not-increase gates
        gates = [("readable", "decrease"), ("writable_cli", "decrease"),
                 ("full", "decrease"),
                 ("read_broken", "increase"), ("write_broken", "increase")]
        failures = []
        for key, direction in gates:
            old, new = base.get(key), counts.get(key)
            if old is None:
                continue
            if direction == "decrease" and new < old:
                failures.append(f"{key} regressed: {old} -> {new}")
            if direction == "increase" and new > old:
                failures.append(f"{key} regressed: {old} -> {new}")
        for key in sorted(set(base) | set(counts)):
            if base.get(key) != counts.get(key):
                print(f"  delta {key}: {base.get(key)} -> {counts.get(key)}")
        if failures:
            print("\nBASELINE REGRESSION:")
            for f in failures:
                print(f"  ✗ {f}")
            print("If intentional, rerun with --update-baseline and commit "
                  f"{BASELINE.name}.")
            sys.exit(1)
        print("Baseline check passed")


if __name__ == "__main__":
    main()
