//! Auto-generated tag database from ExifTool source
//!
//! THIS FILE IS AUTO-GENERATED BY build.rs
//! DO NOT EDIT MANUALLY - CHANGES WILL BE OVERWRITTEN
//!
//! Generated from ExifTool: https://github.com/exiftool/exiftool
//! Total tags: 32677 across 124 format families

#![allow(dead_code)]

use crate::tag_db::TagDescriptor;
use once_cell::sync::Lazy;
use std::collections::HashMap;

// Format family submodules (generated)
#[path = "generated/tags_misb.rs"]
mod tags_misb; // 192 tags
#[path = "generated/tags_pcx.rs"]
mod tags_pcx; // 21 tags
#[path = "generated/tags_zisraw.rs"]
mod tags_zisraw; // 3 tags
#[path = "generated/tags_gm.rs"]
mod tags_gm; // 2 tags
#[path = "generated/tags_moi.rs"]
mod tags_moi; // 9 tags
#[path = "generated/tags_phaseone.rs"]
mod tags_phaseone; // 52 tags
#[path = "generated/tags_miff.rs"]
mod tags_miff; // 4 tags
#[path = "generated/tags_reconyx.rs"]
mod tags_reconyx; // 114 tags
#[path = "generated/tags_h264.rs"]
mod tags_h264; // 68 tags
#[path = "generated/tags_sony.rs"]
mod tags_sony; // 1886 tags
#[path = "generated/tags_real.rs"]
mod tags_real; // 120 tags
#[path = "generated/tags_panasonic.rs"]
mod tags_panasonic; // 418 tags
#[path = "generated/tags_png.rs"]
mod tags_png; // 92 tags
#[path = "generated/tags_mpc.rs"]
mod tags_mpc; // 16 tags
#[path = "generated/tags_kyoceraraw.rs"]
mod tags_kyoceraraw; // 11 tags
#[path = "generated/tags_sonyidc.rs"]
mod tags_sonyidc; // 86 tags
#[path = "generated/tags_panasonicraw.rs"]
mod tags_panasonicraw; // 109 tags
#[path = "generated/tags_stim.rs"]
mod tags_stim; // 38 tags
#[path = "generated/tags_jpeg.rs"]
mod tags_jpeg; // 72 tags
#[path = "generated/tags_mie.rs"]
mod tags_mie; // 11 tags
#[path = "generated/tags_bmp.rs"]
mod tags_bmp; // 40 tags
#[path = "generated/tags_flir.rs"]
mod tags_flir; // 235 tags
#[path = "generated/tags_red.rs"]
mod tags_red; // 26 tags
#[path = "generated/tags_pdf.rs"]
mod tags_pdf; // 10 tags
#[path = "generated/tags_macos.rs"]
mod tags_macos; // 33 tags
#[path = "generated/tags_aac.rs"]
mod tags_aac; // 7 tags
#[path = "generated/tags_iptc.rs"]
mod tags_iptc; // 174 tags
#[path = "generated/tags_kodak.rs"]
mod tags_kodak; // 443 tags
#[path = "generated/tags_microsoft.rs"]
mod tags_microsoft; // 60 tags
#[path = "generated/tags_motorola.rs"]
mod tags_motorola; // 5 tags
#[path = "generated/tags_zip.rs"]
mod tags_zip; // 65 tags
#[path = "generated/tags_vcard.rs"]
mod tags_vcard; // 13 tags
#[path = "generated/tags_lnk.rs"]
mod tags_lnk; // 142 tags
#[path = "generated/tags_bpg.rs"]
mod tags_bpg; // 24 tags
#[path = "generated/tags_exe.rs"]
mod tags_exe; // 255 tags
#[path = "generated/tags_nikoncapture.rs"]
mod tags_nikoncapture; // 155 tags
#[path = "generated/tags_m2ts.rs"]
mod tags_m2ts; // 32 tags
#[path = "generated/tags_minolta.rs"]
mod tags_minolta; // 630 tags
#[path = "generated/tags_nikonsettings.rs"]
mod tags_nikonsettings; // 969 tags
#[path = "generated/tags_trailer.rs"]
mod tags_trailer; // 4 tags
#[path = "generated/tags_vorbis.rs"]
mod tags_vorbis; // 9 tags
#[path = "generated/tags_casio.rs"]
mod tags_casio; // 930 tags
#[path = "generated/tags_gopro.rs"]
mod tags_gopro; // 50 tags
#[path = "generated/tags_riff.rs"]
mod tags_riff; // 110 tags
#[path = "generated/tags_mng.rs"]
mod tags_mng; // 133 tags
#[path = "generated/tags_gimp.rs"]
mod tags_gimp; // 27 tags
#[path = "generated/tags_fits.rs"]
mod tags_fits; // 4 tags
#[path = "generated/tags_ico.rs"]
mod tags_ico; // 7 tags
#[path = "generated/tags_wavpack.rs"]
mod tags_wavpack; // 1 tags
#[path = "generated/tags_minoltaraw.rs"]
mod tags_minoltaraw; // 50 tags
#[path = "generated/tags_palm.rs"]
mod tags_palm; // 78 tags
#[path = "generated/tags_flac.rs"]
mod tags_flac; // 39 tags
#[path = "generated/tags_mxf.rs"]
mod tags_mxf; // 1660 tags
#[path = "generated/tags_parrot.rs"]
mod tags_parrot; // 134 tags
#[path = "generated/tags_photoshop.rs"]
mod tags_photoshop; // 136 tags
#[path = "generated/tags_wtv.rs"]
mod tags_wtv; // 31 tags
#[path = "generated/tags_pentax.rs"]
mod tags_pentax; // 876 tags
#[path = "generated/tags_olympus.rs"]
mod tags_olympus; // 790 tags
#[path = "generated/tags_nikoncustom.rs"]
mod tags_nikoncustom; // 3512 tags
#[path = "generated/tags_canoncustom.rs"]
mod tags_canoncustom; // 429 tags
#[path = "generated/tags_torrent.rs"]
mod tags_torrent; // 18 tags
#[path = "generated/tags_infiray.rs"]
mod tags_infiray; // 80 tags
#[path = "generated/tags_dsf.rs"]
mod tags_dsf; // 14 tags
#[path = "generated/tags_quicktime.rs"]
mod tags_quicktime; // 3063 tags
#[path = "generated/tags_pict.rs"]
mod tags_pict; // 144 tags
#[path = "generated/tags_mpf.rs"]
mod tags_mpf; // 47 tags
#[path = "generated/tags_rsrc.rs"]
mod tags_rsrc; // 3 tags
#[path = "generated/tags_matroska.rs"]
mod tags_matroska; // 242 tags
#[path = "generated/tags_fujifilm.rs"]
mod tags_fujifilm; // 265 tags
#[path = "generated/tags_ricoh.rs"]
mod tags_ricoh; // 198 tags
#[path = "generated/tags_ge.rs"]
mod tags_ge; // 3 tags
#[path = "generated/tags_dpx.rs"]
mod tags_dpx; // 105 tags
#[path = "generated/tags_dicom.rs"]
mod tags_dicom; // 3149 tags
#[path = "generated/tags_canonraw.rs"]
mod tags_canonraw; // 89 tags
#[path = "generated/tags_google.rs"]
mod tags_google; // 35 tags
#[path = "generated/tags_dng.rs"]
mod tags_dng; // 23 tags
#[path = "generated/tags_sanyo.rs"]
mod tags_sanyo; // 93 tags
#[path = "generated/tags_mrc.rs"]
mod tags_mrc; // 139 tags
#[path = "generated/tags_nikon.rs"]
mod tags_nikon; // 2398 tags
#[path = "generated/tags_djvu.rs"]
mod tags_djvu; // 9 tags
#[path = "generated/tags_pcap.rs"]
mod tags_pcap; // 191 tags
#[path = "generated/tags_sigma.rs"]
mod tags_sigma; // 78 tags
#[path = "generated/tags_xmp.rs"]
mod tags_xmp; // 102 tags
#[path = "generated/tags_tnef.rs"]
mod tags_tnef; // 84 tags
#[path = "generated/tags_app12.rs"]
mod tags_app12; // 4 tags
#[path = "generated/tags_icc_profile.rs"]
mod tags_icc_profile; // 90 tags
#[path = "generated/tags_jpeg2000.rs"]
mod tags_jpeg2000; // 61 tags
#[path = "generated/tags_sigmaraw.rs"]
mod tags_sigmaraw; // 23 tags
#[path = "generated/tags_wpg.rs"]
mod tags_wpg; // 86 tags
#[path = "generated/tags_nintendo.rs"]
mod tags_nintendo; // 9 tags
#[path = "generated/tags_photomechanic.rs"]
mod tags_photomechanic; // 23 tags
#[path = "generated/tags_hp.rs"]
mod tags_hp; // 12 tags
#[path = "generated/tags_apple.rs"]
mod tags_apple; // 52 tags
#[path = "generated/tags_postscript.rs"]
mod tags_postscript; // 8 tags
#[path = "generated/tags_theora.rs"]
mod tags_theora; // 17 tags
#[path = "generated/tags_mwg.rs"]
mod tags_mwg; // 36 tags
#[path = "generated/tags_mpeg.rs"]
mod tags_mpeg; // 55 tags
#[path = "generated/tags_jvc.rs"]
mod tags_jvc; // 4 tags
#[path = "generated/tags_itc.rs"]
mod tags_itc; // 7 tags
#[path = "generated/tags_flashpix.rs"]
mod tags_flashpix; // 324 tags
#[path = "generated/tags_xisf.rs"]
mod tags_xisf; // 1 tags
#[path = "generated/tags_fotostation.rs"]
mod tags_fotostation; // 14 tags
#[path = "generated/tags_gif.rs"]
mod tags_gif; // 16 tags
#[path = "generated/tags_font.rs"]
mod tags_font; // 45 tags
#[path = "generated/tags_iso.rs"]
mod tags_iso; // 25 tags
#[path = "generated/tags_ape.rs"]
mod tags_ape; // 18 tags
#[path = "generated/tags_psp.rs"]
mod tags_psp; // 24 tags
#[path = "generated/tags_exif.rs"]
mod tags_exif; // 718 tags
#[path = "generated/tags_opus.rs"]
mod tags_opus; // 6 tags
#[path = "generated/tags_geotiff.rs"]
mod tags_geotiff; // 1916 tags
#[path = "generated/tags_gps.rs"]
mod tags_gps; // 43 tags
#[path = "generated/tags_flash.rs"]
mod tags_flash; // 34 tags
#[path = "generated/tags_openexr.rs"]
mod tags_openexr; // 13 tags
#[path = "generated/tags_html.rs"]
mod tags_html; // 23 tags
#[path = "generated/tags_unknown.rs"]
mod tags_unknown; // 1 tags
#[path = "generated/tags_id3.rs"]
mod tags_id3; // 30 tags
#[path = "generated/tags_canon.rs"]
mod tags_canon; // 2146 tags
#[path = "generated/tags_asf.rs"]
mod tags_asf; // 62 tags
#[path = "generated/tags_pgf.rs"]
mod tags_pgf; // 16 tags
#[path = "generated/tags_dji.rs"]
mod tags_dji; // 186 tags
#[path = "generated/tags_plist.rs"]
mod tags_plist; // 21 tags
#[path = "generated/tags_flif.rs"]
mod tags_flif; // 6 tags
#[path = "generated/tags_photocd.rs"]
mod tags_photocd; // 265 tags
#[path = "generated/tags_aiff.rs"]
mod tags_aiff; // 13 tags

/// Looks up a tag descriptor by its canonical name
/// Queries each format family registry sequentially
pub fn get_generated_tag_descriptor(name: &str) -> Option<&'static TagDescriptor> {
    if let Some(desc) = tags_misb::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_pcx::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_zisraw::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_gm::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_moi::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_phaseone::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_miff::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_reconyx::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_h264::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_sony::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_real::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_panasonic::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_png::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_mpc::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_kyoceraraw::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_sonyidc::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_panasonicraw::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_stim::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_jpeg::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_mie::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_bmp::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_flir::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_red::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_pdf::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_macos::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_aac::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_iptc::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_kodak::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_microsoft::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_motorola::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_zip::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_vcard::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_lnk::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_bpg::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_exe::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_nikoncapture::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_m2ts::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_minolta::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_nikonsettings::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_trailer::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_vorbis::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_casio::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_gopro::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_riff::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_mng::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_gimp::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_fits::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_ico::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_wavpack::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_minoltaraw::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_palm::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_flac::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_mxf::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_parrot::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_photoshop::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_wtv::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_pentax::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_olympus::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_nikoncustom::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_canoncustom::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_torrent::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_infiray::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_dsf::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_quicktime::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_pict::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_mpf::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_rsrc::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_matroska::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_fujifilm::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_ricoh::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_ge::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_dpx::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_dicom::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_canonraw::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_google::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_dng::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_sanyo::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_mrc::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_nikon::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_djvu::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_pcap::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_sigma::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_xmp::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_tnef::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_app12::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_icc_profile::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_jpeg2000::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_sigmaraw::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_wpg::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_nintendo::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_photomechanic::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_hp::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_apple::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_postscript::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_theora::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_mwg::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_mpeg::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_jvc::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_itc::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_flashpix::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_xisf::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_fotostation::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_gif::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_font::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_iso::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_ape::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_psp::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_exif::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_opus::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_geotiff::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_gps::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_flash::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_openexr::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_html::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_unknown::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_id3::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_canon::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_asf::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_pgf::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_dji::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_plist::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_flif::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_photocd::get_tags().get(name) {
        return Some(desc);
    }
    if let Some(desc) = tags_aiff::get_tags().get(name) {
        return Some(desc);
    }
    None
}

/// Returns the total number of registered tags across all families
pub fn generated_tag_count() -> usize {
    32677
}

/// Combined registry - lazily merged from all families on first access
/// WARNING: First access will merge 32K+ tags and may take a few hundred milliseconds
pub static GENERATED_TAG_REGISTRY: Lazy<HashMap<String, TagDescriptor>> = Lazy::new(|| {
    let mut registry = HashMap::with_capacity(32677);
    registry.extend(tags_misb::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_pcx::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_zisraw::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_gm::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_moi::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_phaseone::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_miff::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_reconyx::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_h264::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_sony::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_real::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_panasonic::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_png::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_mpc::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_kyoceraraw::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_sonyidc::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_panasonicraw::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_stim::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_jpeg::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_mie::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_bmp::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_flir::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_red::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_pdf::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_macos::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_aac::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_iptc::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_kodak::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_microsoft::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_motorola::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_zip::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_vcard::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_lnk::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_bpg::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_exe::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_nikoncapture::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_m2ts::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_minolta::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_nikonsettings::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_trailer::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_vorbis::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_casio::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_gopro::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_riff::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_mng::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_gimp::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_fits::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_ico::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_wavpack::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_minoltaraw::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_palm::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_flac::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_mxf::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_parrot::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_photoshop::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_wtv::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_pentax::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_olympus::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_nikoncustom::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_canoncustom::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_torrent::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_infiray::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_dsf::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_quicktime::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_pict::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_mpf::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_rsrc::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_matroska::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_fujifilm::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_ricoh::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_ge::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_dpx::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_dicom::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_canonraw::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_google::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_dng::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_sanyo::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_mrc::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_nikon::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_djvu::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_pcap::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_sigma::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_xmp::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_tnef::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_app12::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_icc_profile::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_jpeg2000::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_sigmaraw::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_wpg::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_nintendo::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_photomechanic::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_hp::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_apple::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_postscript::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_theora::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_mwg::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_mpeg::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_jvc::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_itc::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_flashpix::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_xisf::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_fotostation::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_gif::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_font::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_iso::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_ape::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_psp::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_exif::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_opus::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_geotiff::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_gps::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_flash::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_openexr::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_html::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_unknown::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_id3::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_canon::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_asf::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_pgf::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_dji::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_plist::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_flif::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_photocd::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry.extend(tags_aiff::get_tags().iter().map(|(k, v)| (k.clone(), v.clone())));
    registry
});

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generated_registry_not_empty() {
        assert!(generated_tag_count() > 0);
    }

    #[test]
    fn test_generated_registry_min_count() {
        assert!(generated_tag_count() >= 500);
    }
}
