#ifndef EXIFTOOL_RS_H
#define EXIFTOOL_RS_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/*
 Success code
 */
#define EXIFTOOL_OK 0

/*
 I/O error (file not found, permission denied, etc.)
 */
#define EXIFTOOL_ERR_IO 1

/*
 Parse error (corrupted file, invalid format)
 */
#define EXIFTOOL_ERR_PARSE 2

/*
 Tag not found
 */
#define EXIFTOOL_ERR_TAG_NOT_FOUND 3

/*
 Invalid tag value (type mismatch, out of range)
 */
#define EXIFTOOL_ERR_INVALID_TAG_VALUE 4

/*
 Unsupported format
 */
#define EXIFTOOL_ERR_UNSUPPORTED_FORMAT 5

/*
 NULL pointer provided
 */
#define EXIFTOOL_ERR_NULL_POINTER 6

/*
 Internal error (panic caught)
 */
#define EXIFTOOL_ERR_INTERNAL 99

/*
 Unknown machine type
 */
#define IMAGE_FILE_MACHINE_UNKNOWN 0

/*
 Intel 386+
 */
#define IMAGE_FILE_MACHINE_I386 332

/*
 MIPS R3000
 */
#define IMAGE_FILE_MACHINE_R3000 354

/*
 MIPS R4000
 */
#define IMAGE_FILE_MACHINE_R4000 358

/*
 MIPS R10000
 */
#define IMAGE_FILE_MACHINE_R10000 360

/*
 Alpha AXP
 */
#define IMAGE_FILE_MACHINE_ALPHA 388

/*
 PowerPC
 */
#define IMAGE_FILE_MACHINE_POWERPC 496

/*
 Intel Itanium
 */
#define IMAGE_FILE_MACHINE_IA64 512

/*
 AMD64 (x64)
 */
#define IMAGE_FILE_MACHINE_AMD64 34404

/*
 ARM
 */
#define IMAGE_FILE_MACHINE_ARM 448

/*
 ARM64
 */
#define IMAGE_FILE_MACHINE_ARM64 43620

/*
 Unknown subsystem
 */
#define IMAGE_SUBSYSTEM_UNKNOWN 0

/*
 Native (driver)
 */
#define IMAGE_SUBSYSTEM_NATIVE 1

/*
 Windows GUI
 */
#define IMAGE_SUBSYSTEM_WINDOWS_GUI 2

/*
 Windows Console
 */
#define IMAGE_SUBSYSTEM_WINDOWS_CUI 3

/*
 OS/2 Console
 */
#define IMAGE_SUBSYSTEM_OS2_CUI 5

/*
 POSIX Console
 */
#define IMAGE_SUBSYSTEM_POSIX_CUI 7

/*
 EFI Application
 */
#define IMAGE_SUBSYSTEM_EFI_APPLICATION 10

/*
 EFI Boot Service
 */
#define IMAGE_SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER 11

/*
 EFI Runtime Driver
 */
#define IMAGE_SUBSYSTEM_EFI_RUNTIME_DRIVER 12

/*
 Xbox
 */
#define IMAGE_SUBSYSTEM_XBOX 14

/*
 Opaque handle type for C API.
 C code receives a pointer to this type but cannot access its contents.
 */
typedef struct ExifToolHandle {
    uint8_t _private[0];
} ExifToolHandle;

/*
 Creates a new ExifTool handle.

 # Returns
 - Pointer to opaque handle on success
 - NULL if allocation fails (out of memory)

 # Memory
 The returned handle must be destroyed with `exiftool_destroy()` to prevent memory leaks.

 # Thread Safety
 This function is thread-safe. Each call returns an independent handle.
 */
struct ExifToolHandle *exiftool_create(void);

/*
 Destroys a handle and frees all associated resources.

 # Arguments
 - `handle`: Handle to destroy (can be NULL, in which case this is a no-op)

 # Safety
 After this call, the handle pointer is invalid and must not be used.
 Passing NULL is safe and does nothing.

 # Thread Safety
 Not thread-safe. Do not call concurrently with other operations on the same handle.
 */
void exiftool_destroy(struct ExifToolHandle *handle);

/*
 Reads metadata from a file.

 # Arguments
 - `handle`: Handle to store metadata in (must not be NULL)
 - `filepath`: Path to file (null-terminated UTF-8 string, must not be NULL)

 # Returns
 - `EXIFTOOL_OK` (0) on success
 - Error code on failure

 # Errors
 - `EXIFTOOL_ERR_NULL_POINTER`: handle or filepath is NULL
 - `EXIFTOOL_ERR_IO`: File not found, permission denied, or read error
 - `EXIFTOOL_ERR_UNSUPPORTED_FORMAT`: File format not recognized
 - `EXIFTOOL_ERR_PARSE`: File is corrupted or malformed

 # Thread Safety
 Not thread-safe. Do not call concurrently on the same handle.
 */
int exiftool_read_file(struct ExifToolHandle *handle, const char *filepath);

/*
 Returns the number of tags in the metadata.

 # Arguments
 - `handle`: Handle to query (can be NULL)

 # Returns
 Number of tags (0 if handle is NULL or no metadata loaded)

 # Thread Safety
 Thread-safe for read-only access.
 */
uintptr_t exiftool_get_tag_count(const struct ExifToolHandle *handle);

/*
 Retrieves tag name by index.

 # Arguments
 - `handle`: Handle to query (must not be NULL)
 - `index`: Zero-based index (must be less than tag count)

 # Returns
 - Pointer to null-terminated tag name string
 - NULL if index is out of bounds or handle is NULL

 # String Lifetime
 Returned string is valid until:
 - Next API call on same handle
 - Handle destruction

 # Thread Safety
 Thread-safe for read-only access.
 */
const char *exiftool_get_tag_name_at(const struct ExifToolHandle *handle, uintptr_t index);

/*
 Checks if a tag exists.

 # Arguments
 - `handle`: Handle to query (can be NULL)
 - `tag_name`: Tag name to check (must not be NULL)

 # Returns
 - 1 if tag exists
 - 0 if tag does not exist, handle is NULL, or tag_name is NULL

 # Thread Safety
 Thread-safe for read-only access.
 */
int exiftool_has_tag(const struct ExifToolHandle *handle, const char *tag_name);

/*
 Retrieves tag value as a string.

 # Arguments
 - `handle`: Handle to query (must not be NULL)
 - `tag_name`: Tag name (must not be NULL)

 # Returns
 - Pointer to null-terminated UTF-8 string
 - NULL if tag doesn't exist or is not a String type

 # String Lifetime
 Returned string is valid until:
 - Next API call on same handle
 - Handle destruction

 # Thread Safety
 Thread-safe for read-only access.
 */
const char *exiftool_get_tag_string(const struct ExifToolHandle *handle, const char *tag_name);

/*
 Retrieves tag value as a 64-bit integer.

 # Arguments
 - `handle`: Handle to query (must not be NULL)
 - `tag_name`: Tag name (must not be NULL)
 - `out_value`: Pointer to output variable (must not be NULL)

 # Returns
 - `EXIFTOOL_OK` on success
 - `EXIFTOOL_ERR_TAG_NOT_FOUND` if tag doesn't exist
 - `EXIFTOOL_ERR_INVALID_TAG_VALUE` if tag is not an Integer type
 - `EXIFTOOL_ERR_NULL_POINTER` if any parameter is NULL

 # Thread Safety
 Thread-safe for read-only access.
 */
int exiftool_get_tag_integer(const struct ExifToolHandle *handle,
                             const char *tag_name,
                             int64_t *out_value);

/*
 Retrieves tag value as a double-precision float.

 # Arguments
 - `handle`: Handle to query (must not be NULL)
 - `tag_name`: Tag name (must not be NULL)
 - `out_value`: Pointer to output variable (must not be NULL)

 # Returns
 - `EXIFTOOL_OK` on success
 - `EXIFTOOL_ERR_TAG_NOT_FOUND` if tag doesn't exist
 - `EXIFTOOL_ERR_INVALID_TAG_VALUE` if tag is not a Float type
 - `EXIFTOOL_ERR_NULL_POINTER` if any parameter is NULL

 # Thread Safety
 Thread-safe for read-only access.
 */
int exiftool_get_tag_float(const struct ExifToolHandle *handle,
                           const char *tag_name,
                           double *out_value);

/*
 Sets a tag value to a string.

 # Arguments
 - `handle`: Handle to modify (must not be NULL)
 - `tag_name`: Tag name (must not be NULL)
 - `value`: String value to set (null-terminated UTF-8, must not be NULL)

 # Returns
 - `EXIFTOOL_OK` on success
 - `EXIFTOOL_ERR_NULL_POINTER` if any parameter is NULL

 # Thread Safety
 Not thread-safe. Do not call concurrently on the same handle.
 */
int exiftool_set_tag_string(struct ExifToolHandle *handle, const char *tag_name, const char *value);

/*
 Sets a tag value to an integer.

 # Arguments
 - `handle`: Handle to modify (must not be NULL)
 - `tag_name`: Tag name (must not be NULL)
 - `value`: Integer value to set

 # Returns
 - `EXIFTOOL_OK` on success
 - `EXIFTOOL_ERR_NULL_POINTER` if handle or tag_name is NULL

 # Thread Safety
 Not thread-safe.
 */
int exiftool_set_tag_integer(struct ExifToolHandle *handle, const char *tag_name, int64_t value);

/*
 Sets a tag value to a floating-point number.

 # Arguments
 - `handle`: Handle to modify (must not be NULL)
 - `tag_name`: Tag name (must not be NULL)
 - `value`: Float value to set

 # Returns
 - `EXIFTOOL_OK` on success
 - `EXIFTOOL_ERR_NULL_POINTER` if handle or tag_name is NULL
 - `EXIFTOOL_ERR_INVALID_TAG_VALUE` if value is NaN or infinity

 # Thread Safety
 Not thread-safe.
 */
int exiftool_set_tag_float(struct ExifToolHandle *handle, const char *tag_name, double value);

/*
 Removes a tag from the metadata.

 # Arguments
 - `handle`: Handle to modify (must not be NULL)
 - `tag_name`: Tag name to remove (must not be NULL)

 # Returns
 - `EXIFTOOL_OK` (always succeeds, even if tag didn't exist)
 - `EXIFTOOL_ERR_NULL_POINTER` if handle or tag_name is NULL

 # Thread Safety
 Not thread-safe.
 */
int exiftool_remove_tag(struct ExifToolHandle *handle, const char *tag_name);

/*
 Writes metadata to a file.

 # Arguments
 - `handle`: Handle containing metadata to write (must not be NULL)
 - `filepath`: Path to file to write (null-terminated UTF-8, must not be NULL)

 # Returns
 - `EXIFTOOL_OK` on success
 - Error code on failure

 # Errors
 - `EXIFTOOL_ERR_NULL_POINTER`: handle or filepath is NULL
 - `EXIFTOOL_ERR_IO`: File not writable, disk full, permission denied
 - `EXIFTOOL_ERR_UNSUPPORTED_FORMAT`: File format doesn't support writing
 - `EXIFTOOL_ERR_INVALID_TAG_VALUE`: Metadata validation failed

 # Thread Safety
 Thread-safe for read-only access to handle.
 */
int exiftool_write_file(const struct ExifToolHandle *handle, const char *filepath);

/*
 Retrieves the last error message.

 # Returns
 Pointer to null-terminated error message string.
 Never returns NULL (returns "No error" if no error occurred).

 # String Lifetime
 The returned string is valid until:
 - Next API call that sets an error on the same thread
 - Thread termination

 # Thread Safety
 Thread-safe. Each thread has its own error message.
 */
const char *exiftool_get_last_error(void);

#endif  /* EXIFTOOL_RS_H */
